spring:
  application:
    name: fullstack-app
  datasource:
    url: jdbc:mysql://localhost:3306/todo?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    show-sql: true
  flyway:
    baseline-on-migrate: true
